# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test and Deploy - Node.js CI

env:
  TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
  DB_URL: ${{ secrets.DB_URL }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install Angular Frontend Dependencies 
      working-directory: ./ScholarshipFrontEnd
      run: npm ci
      
    - name: Install Express Backend Dependencies 
      working-directory: ./ScholarshipServer
      run: npm ci
      
    - name: Build Angular Frontend 
      working-directory: ./ScholarshipFrontEnd
      run: npm run build:prod
      
    - name: Build Express Backend 
      working-directory: ./ScholarshipServer
      run: npm run build --if-present
      
    - name: Run Tests 
      working-directory: ./ScholarshipServer
      run: npm run test